### ISSUE TITLE
Camera Button missing in version v1.2.0.1

### ISSUE THREAD

**Issue by eikebartels** [zendesk/zendesk_sdk_chat_ios#64]
The camera button is missing in the version v1.2.0.1. The button is there in the view hierarchy but not visible anymore. 
![simulator screen shot 9 mar 2016 16 54 16](https://cloud.githubusercontent.com/assets/767979/13641111/959fe262-e617-11e5-8748-97d110ca8827.png)

**Comment by RonanMcH** [comment]
Hi @eikebartels ,
Which Zopim plan are you on?  Before version 1.2.0.1, the attachments/camera button was there on the chat view but when a image was sent via end-user on the SDK, it would not be received by the agent if they were on the Zopim Lite plan. This is because the Zopim Lite plan doesn't allow file sending.  In version 1.2.0.1, We got rid of the attachments/camera button for the Lite plan users because it wouldn't work.
Thanks,
Ronan.

**Comment by eikebartels** [comment]
Hi @RonanMcH 
Thanks for the info.

**Comment by eikebartels** [comment]
@RonanMcH , 

now I'm using an account which is definitely not a Zopim Lite plan and the camera button is still not visible. 
<img width="401" alt="screen shot 2016-03-10 at 14 42 36" src="https://cloud.githubusercontent.com/assets/767979/13671142/5eee9238-e6ce-11e5-952a-4b64933580a2.png">

**Comment by RonanMcH** [comment]
@eikebartels ,
will you try delete the app off the simulator/device, clean the workspace and, build and run it again? This should fix the problem I hope.
Ronan.

**Comment by eikebartels** [comment]
Hey @RonanMcH , 

unfortunately no. The problem still exist.

**Comment by RonanMcH** [comment]
Hi @eikebartels,
Is file sending enabled on your zopim dashboard? Shown below:
![screen shot 2016-03-10 at 14 10 29](https://cloud.githubusercontent.com/assets/12997923/13671823/0de61ad6-e6ca-11e5-97d0-a2b5d4f99b76.png)
Thanks, 
Ronan.

**Comment by eikebartels** [comment]
@RonanMcH Thanks. Problem solved.
